apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: aula-k8s
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: http
      port: 80        # porta do Service dentro do cluster
      targetPort: 80  # porta do container
      nodePort: 30080 # porta publicada no nรณ (externa)
