apiVersion: v1
kind: ConfigMap
metadata:
  name: web-cm
  namespace: aula-k8s
data:
  index.html: |
    <h1>Olá, Kubernetes!</h1>
    <p>Servido via ConfigMap.</p>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: aula-k8s
spec:
  replicas: 2
  selector:
    matchLabels: { app: web }
  template:
    metadata: { labels: { app: web } }
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports: [{ containerPort: 80 }]
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: web-cm
