apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: aula-k8s
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "64Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hard-limits
  namespace: aula-k8s
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: "1Gi"
    limits.cpu: "4"
    limits.memory: "2Gi"